import type { VehicleRecord } from "./types";

// ---------------------------------------------------------------------------
// Helper: PMT calculation  (standard annuity payment)
// PMT(rate, nper, pv) = pv * rate / (1 - (1+rate)^-nper)
// ---------------------------------------------------------------------------
function pmt(annualRate: number, months: number, principal: number): number {
  const r = annualRate / 100 / 12;
  if (r === 0) return Math.round(principal / months);
  return Math.round((principal * r) / (1 - Math.pow(1 + r, -months)));
}

function buildVehicle(
  partial: Omit<
    VehicleRecord,
    "total_savings" | "est_monthly_payment"
  >,
): VehicleRecord {
  const total_savings = partial.msrp - partial.sale_price;
  const financed = partial.sale_price - partial.finance_down_payment;
  const est_monthly_payment = pmt(
    partial.finance_apr,
    partial.finance_term_months,
    financed,
  );
  return { ...partial, total_savings, est_monthly_payment } as VehicleRecord;
}

// Helper to generate a VIN-like string
function vin(seed: string): string {
  return seed.padEnd(17, "0").slice(0, 17).toUpperCase();
}

export const MOCK_VEHICLES: VehicleRecord[] = [
  // ---- Ford ----------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_001",
    year: 2024,
    make: "Ford",
    model: "F-150",
    trim: "XLT SuperCrew",
    condition: "New",
    body_style: "Truck",
    stock_number: "F240101",
    vin: vin("1FTEW1EP5RFA01001"),
    exterior_color_label: "Iconic Silver Metallic",
    exterior_color_hex: "#A8A9AD",
    interior_color: "Medium Dark Slate",
    interior_material: "Cloth",
    transmission: "Automatic",
    drivetrain: "4WD",
    engine: "3.5L V6 EcoBoost",
    cylinders: 6,
    horsepower: 400,
    torque: 500,
    fuel_type: "Gasoline",
    mpg_city: 18,
    mpg_hwy: 24,
    ev_range_miles: null,
    mileage: 12,
    msrp: 52490,
    sale_price: 49995,
    dealer_discount: 2495,
    manufacturer_incentive: 0,
    finance_apr: 5.9,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["XLT Series", "Tow Technology Pkg"],
    addon_options: ["Spray-in bedliner", "Running boards"],
    standard_features: ["Apple CarPlay", "Android Auto", "Sync 4", "Pro Trailer Backup Assist"],
    safety_features: ["Pre-Collision Assist", "Blind Spot Monitor", "Lane Keep Assist", "Rear View Camera"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "5yr / 60,000 mi",
    photos: ["/vehicles/ford-f150-1.jpg", "/vehicles/ford-f150-2.jpg", "/vehicles/ford-f150-3.jpg"],
    video_url: null,
    days_on_lot: 14,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  buildVehicle({
    vehicle_id: "veh_002",
    year: 2023,
    make: "Ford",
    model: "Explorer",
    trim: "ST-Line",
    condition: "Used",
    body_style: "SUV",
    stock_number: "F230201",
    vin: vin("1FMSK8GC9PGA02002"),
    exterior_color_label: "Agate Black Metallic",
    exterior_color_hex: "#1a1a1a",
    interior_color: "Ebony Black",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "2.3L I4 EcoBoost",
    cylinders: 4,
    horsepower: 300,
    torque: 310,
    fuel_type: "Gasoline",
    mpg_city: 21,
    mpg_hwy: 28,
    ev_range_miles: null,
    mileage: 24350,
    msrp: 46895,
    sale_price: 38750,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 6.4,
    finance_term_months: 60,
    finance_down_payment: 4000,
    factory_packages: ["ST-Line Appearance Pkg"],
    addon_options: ["All-weather floor mats"],
    standard_features: ["Apple CarPlay", "Wireless Charging", "Heated Seats", "Power Liftgate"],
    safety_features: ["Co-Pilot360", "Blind Spot Assist", "Cross Traffic Alert", "Lane Keep Assist"],
    warranty_basic: "Expired",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "Expired",
    photos: ["/vehicles/ford-explorer-1.jpg", "/vehicles/ford-explorer-2.jpg"],
    video_url: null,
    days_on_lot: 28,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=1FMSK8GC9PGA02002",
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_003",
    year: 2024,
    make: "Ford",
    model: "Mustang Mach-E",
    trim: "Premium AWD",
    condition: "New",
    body_style: "SUV",
    stock_number: "F240301",
    vin: vin("3FTTW8E35RWA03003"),
    exterior_color_label: "Grabber Blue Metallic",
    exterior_color_hex: "#007DBA",
    interior_color: "Space Gray",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "Dual Electric Motor",
    cylinders: 0,
    horsepower: 346,
    torque: 428,
    fuel_type: "Electric",
    mpg_city: 0,
    mpg_hwy: 0,
    ev_range_miles: 290,
    mileage: 5,
    msrp: 51275,
    sale_price: 48990,
    dealer_discount: 1285,
    manufacturer_incentive: 1000,
    finance_apr: 4.9,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["Extended Range Battery", "Comfort & Technology Pkg"],
    addon_options: ["Ford Connected Charge Station"],
    standard_features: ["Sync 4A", "15.5\" Touchscreen", "Phone As Key", "Wireless CarPlay"],
    safety_features: ["BlueCruise", "Evasive Steering Assist", "Reverse Sensing", "360-Degree Camera"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "8yr / 100,000 mi",
    warranty_roadside: "5yr / 60,000 mi",
    photos: ["/vehicles/ford-mach-e-1.jpg", "/vehicles/ford-mach-e-2.jpg", "/vehicles/ford-mach-e-3.jpg"],
    video_url: "https://videos.example.com/mach-e-walkaround.mp4",
    days_on_lot: 7,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  // ---- Toyota --------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_004",
    year: 2024,
    make: "Toyota",
    model: "Camry",
    trim: "XSE V6",
    condition: "New",
    body_style: "Sedan",
    stock_number: "T240401",
    vin: vin("4T1BF3EK5AU040004"),
    exterior_color_label: "Midnight Black Metallic",
    exterior_color_hex: "#1a1a1a",
    interior_color: "Black/Red SofTex",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "FWD",
    engine: "3.5L V6 DOHC 24V",
    cylinders: 6,
    horsepower: 301,
    torque: 267,
    fuel_type: "Gasoline",
    mpg_city: 22,
    mpg_hwy: 31,
    ev_range_miles: null,
    mileage: 8,
    msrp: 38450,
    sale_price: 36995,
    dealer_discount: 1455,
    manufacturer_incentive: 0,
    finance_apr: 5.9,
    finance_term_months: 72,
    finance_down_payment: 3000,
    factory_packages: ["Technology Pkg", "Premium Audio Pkg"],
    addon_options: ["Cargo liner", "Door edge guards"],
    standard_features: ["Apple CarPlay", "Heated seats", "9\" Touchscreen", "Wireless Charging"],
    safety_features: ["Toyota Safety Sense 3.0", "Blind Spot Monitor", "Rear Cross Traffic Alert", "Lane Departure Alert"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "2yr / 25,000 mi",
    photos: ["/vehicles/toyota-camry-1.jpg", "/vehicles/toyota-camry-2.jpg"],
    video_url: null,
    days_on_lot: 21,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_005",
    year: 2023,
    make: "Toyota",
    model: "RAV4",
    trim: "XLE Premium",
    condition: "CPO",
    body_style: "SUV",
    stock_number: "T230501",
    vin: vin("2T3RFREV5PW050005"),
    exterior_color_label: "Blueprint",
    exterior_color_hex: "#2B3C5F",
    interior_color: "Light Gray SofTex",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "2.5L I4 DOHC 16V",
    cylinders: 4,
    horsepower: 203,
    torque: 184,
    fuel_type: "Gasoline",
    mpg_city: 27,
    mpg_hwy: 34,
    ev_range_miles: null,
    mileage: 18420,
    msrp: 36250,
    sale_price: 31499,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 5.4,
    finance_term_months: 60,
    finance_down_payment: 3000,
    factory_packages: ["Advanced Technology Pkg"],
    addon_options: ["Roof rack cross bars"],
    standard_features: ["Apple CarPlay", "Sunroof", "Heated Seats", "Power Liftgate"],
    safety_features: ["Toyota Safety Sense 2.5+", "Blind Spot Monitor", "Rear Cross Traffic Alert"],
    warranty_basic: "CPO: 1yr / 12,000 mi",
    warranty_powertrain: "CPO: 7yr / 100,000 mi",
    warranty_roadside: "CPO: 7yr / 100,000 mi",
    photos: ["/vehicles/toyota-rav4-1.jpg", "/vehicles/toyota-rav4-2.jpg", "/vehicles/toyota-rav4-3.jpg"],
    video_url: null,
    days_on_lot: 10,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=2T3RFREV5PW050005",
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  buildVehicle({
    vehicle_id: "veh_006",
    year: 2022,
    make: "Toyota",
    model: "Tacoma",
    trim: "TRD Off-Road",
    condition: "Used",
    body_style: "Truck",
    stock_number: "T220601",
    vin: vin("3TMCZ5AN0NM060006"),
    exterior_color_label: "Army Green",
    exterior_color_hex: "#4B5320",
    interior_color: "Black Fabric",
    interior_material: "Cloth",
    transmission: "Manual",
    drivetrain: "4WD",
    engine: "3.5L V6",
    cylinders: 6,
    horsepower: 278,
    torque: 265,
    fuel_type: "Gasoline",
    mpg_city: 18,
    mpg_hwy: 22,
    ev_range_miles: null,
    mileage: 32150,
    msrp: 42500,
    sale_price: 37900,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 6.9,
    finance_term_months: 60,
    finance_down_payment: 4000,
    factory_packages: ["TRD Off-Road Pkg", "Technology Pkg"],
    addon_options: ["Bed mat", "Predator tube steps"],
    standard_features: ["Crawl Control", "Multi-Terrain Select", "Apple CarPlay"],
    safety_features: ["Toyota Safety Sense P", "Blind Spot Monitor", "Rear Cross Traffic Alert"],
    warranty_basic: "Expired",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "Expired",
    photos: ["/vehicles/toyota-tacoma-1.jpg", "/vehicles/toyota-tacoma-2.jpg"],
    video_url: null,
    days_on_lot: 45,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=3TMCZ5AN0NM060006",
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_007",
    year: 2024,
    make: "Toyota",
    model: "Highlander",
    trim: "Hybrid Limited",
    condition: "New",
    body_style: "SUV",
    stock_number: "T240701",
    vin: vin("5TDKBRFH9RS070007"),
    exterior_color_label: "Wind Chill Pearl",
    exterior_color_hex: "#E8E4DB",
    interior_color: "Glazed Caramel Leather",
    interior_material: "Leather",
    transmission: "CVT",
    drivetrain: "AWD",
    engine: "2.5L I4 Hybrid",
    cylinders: 4,
    horsepower: 243,
    torque: 175,
    fuel_type: "Hybrid",
    mpg_city: 36,
    mpg_hwy: 35,
    ev_range_miles: null,
    mileage: 15,
    msrp: 51435,
    sale_price: 50299,
    dealer_discount: 636,
    manufacturer_incentive: 500,
    finance_apr: 5.4,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["Premium Audio", "Captain Chairs"],
    addon_options: ["Paint protection film", "Cargo net"],
    standard_features: ["JBL Audio", "Panoramic Moonroof", "Heated/Ventilated Seats", "Head-Up Display"],
    safety_features: ["Toyota Safety Sense 3.0", "Surround View Camera", "Front/Rear Parking Sonar"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "2yr / 25,000 mi",
    photos: ["/vehicles/toyota-highlander-1.jpg", "/vehicles/toyota-highlander-2.jpg"],
    video_url: null,
    days_on_lot: 5,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  // ---- Honda ---------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_008",
    year: 2024,
    make: "Honda",
    model: "Civic",
    trim: "Sport Touring",
    condition: "New",
    body_style: "Hatchback",
    stock_number: "H240801",
    vin: vin("19XFL1H78RE080008"),
    exterior_color_label: "Rallye Red",
    exterior_color_hex: "#C8102E",
    interior_color: "Black Leather",
    interior_material: "Leather",
    transmission: "CVT",
    drivetrain: "FWD",
    engine: "1.5L I4 Turbo",
    cylinders: 4,
    horsepower: 180,
    torque: 177,
    fuel_type: "Gasoline",
    mpg_city: 31,
    mpg_hwy: 38,
    ev_range_miles: null,
    mileage: 22,
    msrp: 32250,
    sale_price: 31450,
    dealer_discount: 800,
    manufacturer_incentive: 0,
    finance_apr: 5.9,
    finance_term_months: 72,
    finance_down_payment: 3000,
    factory_packages: ["HPD Package"],
    addon_options: ["All-season floor mats", "Trunk tray"],
    standard_features: ["Apple CarPlay", "Android Auto", "Bose Audio", "Wireless Charging", "Sunroof"],
    safety_features: ["Honda Sensing", "Blind Spot Info", "Rear Cross Traffic Monitor", "Traffic Jam Assist"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "3yr / 36,000 mi",
    photos: ["/vehicles/honda-civic-1.jpg", "/vehicles/honda-civic-2.jpg", "/vehicles/honda-civic-3.jpg"],
    video_url: null,
    days_on_lot: 18,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_009",
    year: 2023,
    make: "Honda",
    model: "CR-V",
    trim: "EX-L",
    condition: "CPO",
    body_style: "SUV",
    stock_number: "H230901",
    vin: vin("7FARS6H73PE090009"),
    exterior_color_label: "Crystal Black Pearl",
    exterior_color_hex: "#0E0E10",
    interior_color: "Black Leather",
    interior_material: "Leather",
    transmission: "CVT",
    drivetrain: "AWD",
    engine: "1.5L I4 Turbo",
    cylinders: 4,
    horsepower: 190,
    torque: 179,
    fuel_type: "Gasoline",
    mpg_city: 28,
    mpg_hwy: 34,
    ev_range_miles: null,
    mileage: 15200,
    msrp: 38600,
    sale_price: 33495,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 5.4,
    finance_term_months: 60,
    finance_down_payment: 3500,
    factory_packages: [],
    addon_options: ["Roof rails", "Cargo cover"],
    standard_features: ["Apple CarPlay", "Android Auto", "Heated Seats", "Moonroof", "Power Liftgate"],
    safety_features: ["Honda Sensing", "Blind Spot Info", "Rear Cross Traffic", "Hill Descent Control"],
    warranty_basic: "CPO: up to 7yr / 100,000 mi",
    warranty_powertrain: "CPO: up to 7yr / 100,000 mi",
    warranty_roadside: "CPO: included",
    photos: ["/vehicles/honda-crv-1.jpg", "/vehicles/honda-crv-2.jpg"],
    video_url: null,
    days_on_lot: 12,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=7FARS6H73PE090009",
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_010",
    year: 2024,
    make: "Honda",
    model: "Accord",
    trim: "Hybrid Sport-L",
    condition: "New",
    body_style: "Sedan",
    stock_number: "H241001",
    vin: vin("1HGCY2F5XRA100010"),
    exterior_color_label: "Still Night Pearl",
    exterior_color_hex: "#1B2640",
    interior_color: "Black Leather",
    interior_material: "Leather",
    transmission: "CVT",
    drivetrain: "FWD",
    engine: "2.0L I4 Hybrid",
    cylinders: 4,
    horsepower: 204,
    torque: 247,
    fuel_type: "Hybrid",
    mpg_city: 51,
    mpg_hwy: 44,
    ev_range_miles: null,
    mileage: 10,
    msrp: 36990,
    sale_price: 35490,
    dealer_discount: 1000,
    manufacturer_incentive: 500,
    finance_apr: 4.9,
    finance_term_months: 72,
    finance_down_payment: 3000,
    factory_packages: [],
    addon_options: ["All-season floor mats"],
    standard_features: ["Apple CarPlay", "Android Auto", "Google Built-in", "Wireless Charging", "12\" Touchscreen"],
    safety_features: ["Honda Sensing 360", "Blind Spot Info", "Rear Cross Traffic", "Traffic Jam Assist"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "3yr / 36,000 mi",
    photos: ["/vehicles/honda-accord-1.jpg", "/vehicles/honda-accord-2.jpg"],
    video_url: null,
    days_on_lot: 9,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  // ---- Chevrolet -----------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_011",
    year: 2024,
    make: "Chevrolet",
    model: "Silverado 1500",
    trim: "LT Trail Boss",
    condition: "New",
    body_style: "Truck",
    stock_number: "C241101",
    vin: vin("1GCUYEED5RZ110011"),
    exterior_color_label: "Summit White",
    exterior_color_hex: "#F2F2F2",
    interior_color: "Jet Black Cloth",
    interior_material: "Cloth",
    transmission: "Automatic",
    drivetrain: "4WD",
    engine: "5.3L V8 EcoTec3",
    cylinders: 8,
    horsepower: 355,
    torque: 383,
    fuel_type: "Gasoline",
    mpg_city: 16,
    mpg_hwy: 22,
    ev_range_miles: null,
    mileage: 18,
    msrp: 55300,
    sale_price: 52450,
    dealer_discount: 1850,
    manufacturer_incentive: 1000,
    finance_apr: 5.9,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["Z71 Off-Road Pkg", "Convenience Pkg"],
    addon_options: ["Spray-in bedliner", "Tonneau cover"],
    standard_features: ["Apple CarPlay", "Android Auto", "13.4\" Touchscreen", "Trailering Pkg"],
    safety_features: ["Forward Collision Alert", "Lane Keep Assist", "IntelliBeam", "Rear Park Assist"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "5yr / 60,000 mi",
    photos: ["/vehicles/chevrolet-silverado-1.jpg", "/vehicles/chevrolet-silverado-2.jpg"],
    video_url: null,
    days_on_lot: 30,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_012",
    year: 2024,
    make: "Chevrolet",
    model: "Equinox",
    trim: "RS",
    condition: "New",
    body_style: "SUV",
    stock_number: "C241201",
    vin: vin("3GNAXKEV8RS120012"),
    exterior_color_label: "Radiant Red Tintcoat",
    exterior_color_hex: "#8B0000",
    interior_color: "Jet Black / Sky Cool Gray",
    interior_material: "Cloth",
    transmission: "Automatic",
    drivetrain: "FWD",
    engine: "1.5L I4 Turbo",
    cylinders: 4,
    horsepower: 175,
    torque: 203,
    fuel_type: "Gasoline",
    mpg_city: 28,
    mpg_hwy: 33,
    ev_range_miles: null,
    mileage: 5,
    msrp: 33295,
    sale_price: 31499,
    dealer_discount: 1296,
    manufacturer_incentive: 500,
    finance_apr: 4.9,
    finance_term_months: 72,
    finance_down_payment: 2500,
    factory_packages: ["Confidence & Convenience Pkg"],
    addon_options: ["All-weather floor liners"],
    standard_features: ["Apple CarPlay", "Android Auto", "Wireless Charging", "Heated Seats"],
    safety_features: ["Chevy Safety Assist", "Blind Spot Alert", "Rear Cross Traffic", "HD Surround Vision"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "5yr / 60,000 mi",
    photos: ["/vehicles/chevrolet-equinox-1.jpg", "/vehicles/chevrolet-equinox-2.jpg"],
    video_url: null,
    days_on_lot: 11,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  buildVehicle({
    vehicle_id: "veh_013",
    year: 2022,
    make: "Chevrolet",
    model: "Tahoe",
    trim: "LT",
    condition: "Used",
    body_style: "SUV",
    stock_number: "C221301",
    vin: vin("1GNSKBKD5NR130013"),
    exterior_color_label: "Shadow Gray Metallic",
    exterior_color_hex: "#6C6C6C",
    interior_color: "Jet Black Leather",
    interior_material: "Leather",
    transmission: "Automatic",
    drivetrain: "4WD",
    engine: "5.3L V8",
    cylinders: 8,
    horsepower: 355,
    torque: 383,
    fuel_type: "Gasoline",
    mpg_city: 15,
    mpg_hwy: 20,
    ev_range_miles: null,
    mileage: 42100,
    msrp: 62995,
    sale_price: 49800,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 6.9,
    finance_term_months: 60,
    finance_down_payment: 5000,
    factory_packages: ["Z71 Pkg", "Max Trailering Pkg"],
    addon_options: [],
    standard_features: ["Apple CarPlay", "Bose Audio", "Third Row", "Power Liftgate", "Heated Seats"],
    safety_features: ["Forward Collision Alert", "Lane Keep Assist", "Rear Park Assist", "HD Surround Vision"],
    warranty_basic: "Expired",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "Expired",
    photos: ["/vehicles/chevrolet-tahoe-1.jpg", "/vehicles/chevrolet-tahoe-2.jpg"],
    video_url: null,
    days_on_lot: 55,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=1GNSKBKD5NR130013",
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  // ---- BMW -----------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_014",
    year: 2024,
    make: "BMW",
    model: "3 Series",
    trim: "330i xDrive",
    condition: "New",
    body_style: "Sedan",
    stock_number: "B241401",
    vin: vin("WBA53BJ01RWN14014"),
    exterior_color_label: "Alpine White",
    exterior_color_hex: "#F5F5F5",
    interior_color: "Cognac Vernasca Leather",
    interior_material: "Leather",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "2.0L I4 TwinPower Turbo",
    cylinders: 4,
    horsepower: 255,
    torque: 295,
    fuel_type: "Gasoline",
    mpg_city: 26,
    mpg_hwy: 35,
    ev_range_miles: null,
    mileage: 30,
    msrp: 48395,
    sale_price: 47200,
    dealer_discount: 695,
    manufacturer_incentive: 500,
    finance_apr: 5.4,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["Premium Pkg", "M Sport Pkg"],
    addon_options: ["Shadowline exterior trim"],
    standard_features: ["iDrive 8.5", "Harman Kardon Audio", "Heated Seats", "Ambient Lighting", "Wireless Charging"],
    safety_features: ["Driving Assist Pro", "Frontal Collision Warning", "Lane Departure Warning", "Parking Assist"],
    warranty_basic: "4yr / 50,000 mi",
    warranty_powertrain: "4yr / 50,000 mi",
    warranty_roadside: "4yr / unlimited mi",
    photos: ["/vehicles/bmw-3series-1.jpg", "/vehicles/bmw-3series-2.jpg", "/vehicles/bmw-3series-3.jpg"],
    video_url: null,
    days_on_lot: 22,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_015",
    year: 2023,
    make: "BMW",
    model: "X5",
    trim: "xDrive40i",
    condition: "CPO",
    body_style: "SUV",
    stock_number: "B231501",
    vin: vin("5UXCR6C06P9L15015"),
    exterior_color_label: "Phytonic Blue Metallic",
    exterior_color_hex: "#1A3A5C",
    interior_color: "Canberra Beige Leather",
    interior_material: "Leather",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "3.0L I6 TwinPower Turbo",
    cylinders: 6,
    horsepower: 335,
    torque: 331,
    fuel_type: "Gasoline",
    mpg_city: 22,
    mpg_hwy: 27,
    ev_range_miles: null,
    mileage: 21800,
    msrp: 68895,
    sale_price: 55990,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 5.9,
    finance_term_months: 60,
    finance_down_payment: 7000,
    factory_packages: ["Premium Pkg", "Trailer Hitch"],
    addon_options: [],
    standard_features: ["iDrive 8", "Panoramic Moonroof", "Heated Seats", "Gesture Control", "Harman Kardon"],
    safety_features: ["Driving Assist Plus", "Parking Assist Plus", "Surround View", "Active Guard Plus"],
    warranty_basic: "CPO: 1yr / unlimited mi",
    warranty_powertrain: "CPO: to 6yr / 100,000 mi",
    warranty_roadside: "CPO: included",
    photos: ["/vehicles/bmw-x5-1.jpg", "/vehicles/bmw-x5-2.jpg"],
    video_url: "https://videos.example.com/bmw-x5-walkaround.mp4",
    days_on_lot: 16,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=5UXCR6C06P9L15015",
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  // ---- Mercedes-Benz -------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_016",
    year: 2024,
    make: "Mercedes-Benz",
    model: "C-Class",
    trim: "C 300 4MATIC",
    condition: "New",
    body_style: "Sedan",
    stock_number: "M241601",
    vin: vin("W1KAF4GB3RA160016"),
    exterior_color_label: "Obsidian Black Metallic",
    exterior_color_hex: "#0D0D0D",
    interior_color: "Macchiato Beige Leather",
    interior_material: "Leather",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "2.0L I4 Turbo + EQ Boost",
    cylinders: 4,
    horsepower: 255,
    torque: 295,
    fuel_type: "Gasoline",
    mpg_city: 24,
    mpg_hwy: 33,
    ev_range_miles: null,
    mileage: 15,
    msrp: 50650,
    sale_price: 49500,
    dealer_discount: 650,
    manufacturer_incentive: 500,
    finance_apr: 4.9,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["Premium Pkg", "AMG Line"],
    addon_options: ["Illuminated Star"],
    standard_features: ["MBUX", "11.9\" Touchscreen", "Burmester Audio", "Wireless CarPlay", "Heated Seats"],
    safety_features: ["Active Brake Assist", "Blind Spot Assist", "Active Lane Keep Assist", "Attention Assist"],
    warranty_basic: "4yr / 50,000 mi",
    warranty_powertrain: "4yr / 50,000 mi",
    warranty_roadside: "4yr / 50,000 mi",
    photos: ["/vehicles/mercedes-cclass-1.jpg", "/vehicles/mercedes-cclass-2.jpg"],
    video_url: null,
    days_on_lot: 35,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_017",
    year: 2022,
    make: "Mercedes-Benz",
    model: "GLE",
    trim: "GLE 350 4MATIC",
    condition: "Used",
    body_style: "SUV",
    stock_number: "M221701",
    vin: vin("4JGFB4KB7NA170017"),
    exterior_color_label: "Selenite Grey Metallic",
    exterior_color_hex: "#6E7B8B",
    interior_color: "Black MB-Tex",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "2.0L I4 Turbo",
    cylinders: 4,
    horsepower: 255,
    torque: 273,
    fuel_type: "Gasoline",
    mpg_city: 21,
    mpg_hwy: 27,
    ev_range_miles: null,
    mileage: 38600,
    msrp: 62750,
    sale_price: 44995,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 6.9,
    finance_term_months: 60,
    finance_down_payment: 5000,
    factory_packages: ["Premium Pkg"],
    addon_options: [],
    standard_features: ["MBUX", "Panoramic Roof", "Heated Seats", "Power Liftgate", "Burmester Audio"],
    safety_features: ["Active Brake Assist", "Blind Spot Assist", "Active Lane Keep Assist", "PRE-SAFE"],
    warranty_basic: "Expired",
    warranty_powertrain: "Expired",
    warranty_roadside: "Expired",
    photos: ["/vehicles/mercedes-gle-1.jpg", "/vehicles/mercedes-gle-2.jpg"],
    video_url: null,
    days_on_lot: 42,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=4JGFB4KB7NA170017",
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  // ---- Tesla ---------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_018",
    year: 2024,
    make: "Tesla",
    model: "Model 3",
    trim: "Long Range AWD",
    condition: "New",
    body_style: "Sedan",
    stock_number: "T241801",
    vin: vin("5YJ3E1EC2RF180018"),
    exterior_color_label: "Ultra White",
    exterior_color_hex: "#FAFAFA",
    interior_color: "Black Vegan Leather",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "Dual Motor Electric",
    cylinders: 0,
    horsepower: 346,
    torque: 389,
    fuel_type: "Electric",
    mpg_city: 0,
    mpg_hwy: 0,
    ev_range_miles: 358,
    mileage: 3,
    msrp: 47490,
    sale_price: 47490,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 5.4,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: [],
    addon_options: ["Full Self-Driving Capability", "Paint Protection Film"],
    standard_features: ["Autopilot", "15\" Touchscreen", "Glass Roof", "Wireless Phone Charging"],
    safety_features: ["Automatic Emergency Braking", "Lane Departure Avoidance", "Blind Spot Warning", "Side Collision Warning"],
    warranty_basic: "4yr / 50,000 mi",
    warranty_powertrain: "8yr / 120,000 mi",
    warranty_roadside: "4yr / 50,000 mi",
    photos: ["/vehicles/tesla-model3-1.jpg", "/vehicles/tesla-model3-2.jpg", "/vehicles/tesla-model3-3.jpg"],
    video_url: null,
    days_on_lot: 3,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  buildVehicle({
    vehicle_id: "veh_019",
    year: 2023,
    make: "Tesla",
    model: "Model Y",
    trim: "Performance",
    condition: "Used",
    body_style: "SUV",
    stock_number: "T231901",
    vin: vin("7SAYGDEF3PA190019"),
    exterior_color_label: "Midnight Cherry Red",
    exterior_color_hex: "#5B0E2D",
    interior_color: "White Vegan Leather",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "Dual Motor Electric",
    cylinders: 0,
    horsepower: 455,
    torque: 497,
    fuel_type: "Electric",
    mpg_city: 0,
    mpg_hwy: 0,
    ev_range_miles: 303,
    mileage: 12450,
    msrp: 54990,
    sale_price: 44500,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 6.4,
    finance_term_months: 60,
    finance_down_payment: 5000,
    factory_packages: [],
    addon_options: ["Full Self-Driving Capability"],
    standard_features: ["Autopilot", "15\" Touchscreen", "Glass Roof", "Premium Audio", "Heated All Seats"],
    safety_features: ["Automatic Emergency Braking", "Lane Departure Avoidance", "Side Collision Warning"],
    warranty_basic: "4yr / 50,000 mi",
    warranty_powertrain: "8yr / 120,000 mi",
    warranty_roadside: "4yr / 50,000 mi",
    photos: ["/vehicles/tesla-modely-1.jpg", "/vehicles/tesla-modely-2.jpg"],
    video_url: null,
    days_on_lot: 8,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=7SAYGDEF3PA190019",
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  // ---- Jeep ----------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_020",
    year: 2024,
    make: "Jeep",
    model: "Wrangler",
    trim: "Rubicon 4dr",
    condition: "New",
    body_style: "SUV",
    stock_number: "J242001",
    vin: vin("1C4HJXFG1RW200020"),
    exterior_color_label: "Bikini Pearl",
    exterior_color_hex: "#1A8D8D",
    interior_color: "Black Cloth",
    interior_material: "Cloth",
    transmission: "Automatic",
    drivetrain: "4WD",
    engine: "3.6L V6 Pentastar",
    cylinders: 6,
    horsepower: 285,
    torque: 260,
    fuel_type: "Gasoline",
    mpg_city: 17,
    mpg_hwy: 22,
    ev_range_miles: null,
    mileage: 25,
    msrp: 52990,
    sale_price: 51495,
    dealer_discount: 1495,
    manufacturer_incentive: 0,
    finance_apr: 5.9,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["LED Lighting Pkg", "Safety Group"],
    addon_options: ["Hard top", "Jeep trail bag"],
    standard_features: ["Uconnect 5", "Apple CarPlay", "Android Auto", "Rock-Trac 4WD", "Locking Differentials"],
    safety_features: ["Blind Spot Monitor", "Rear Cross Path Detection", "Forward Collision Warning", "ParkSense"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "5yr / 60,000 mi",
    photos: ["/vehicles/jeep-wrangler-1.jpg", "/vehicles/jeep-wrangler-2.jpg", "/vehicles/jeep-wrangler-3.jpg"],
    video_url: "https://videos.example.com/wrangler-trail.mp4",
    days_on_lot: 19,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_021",
    year: 2023,
    make: "Jeep",
    model: "Grand Cherokee",
    trim: "Overland",
    condition: "CPO",
    body_style: "SUV",
    stock_number: "J232101",
    vin: vin("1C4RJKDG2P8210021"),
    exterior_color_label: "Rocky Mountain Pearl",
    exterior_color_hex: "#B0C4DE",
    interior_color: "Tupelo/Black Nappa Leather",
    interior_material: "Leather",
    transmission: "Automatic",
    drivetrain: "4WD",
    engine: "3.6L V6 Pentastar",
    cylinders: 6,
    horsepower: 293,
    torque: 260,
    fuel_type: "Gasoline",
    mpg_city: 19,
    mpg_hwy: 26,
    ev_range_miles: null,
    mileage: 16800,
    msrp: 56525,
    sale_price: 45995,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 5.4,
    finance_term_months: 60,
    finance_down_payment: 5000,
    factory_packages: ["Luxury Tech Group", "Tow Pkg"],
    addon_options: [],
    standard_features: ["Uconnect 5", "McIntosh Audio", "Panoramic Sunroof", "Ventilated Seats", "Head-Up Display"],
    safety_features: ["Active Driving Assist", "Drowsy Driver Detection", "Night Vision", "360-Degree Camera"],
    warranty_basic: "CPO: 3mo / 3,000 mi",
    warranty_powertrain: "CPO: 7yr / 100,000 mi",
    warranty_roadside: "CPO: included",
    photos: ["/vehicles/jeep-grandcherokee-1.jpg", "/vehicles/jeep-grandcherokee-2.jpg"],
    video_url: null,
    days_on_lot: 14,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=1C4RJKDG2P8210021",
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  // ---- Hyundai -------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_022",
    year: 2024,
    make: "Hyundai",
    model: "Tucson",
    trim: "SEL Convenience",
    condition: "New",
    body_style: "SUV",
    stock_number: "H242201",
    vin: vin("KM8J3CAL3RU220022"),
    exterior_color_label: "Shimmering Silver",
    exterior_color_hex: "#C0C0C0",
    interior_color: "Gray Cloth",
    interior_material: "Cloth",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "2.5L I4",
    cylinders: 4,
    horsepower: 187,
    torque: 178,
    fuel_type: "Gasoline",
    mpg_city: 26,
    mpg_hwy: 33,
    ev_range_miles: null,
    mileage: 10,
    msrp: 33150,
    sale_price: 31450,
    dealer_discount: 1200,
    manufacturer_incentive: 500,
    finance_apr: 4.9,
    finance_term_months: 72,
    finance_down_payment: 2500,
    factory_packages: ["Convenience Pkg"],
    addon_options: ["Carpeted floor mats"],
    standard_features: ["Apple CarPlay", "Android Auto", "8\" Touchscreen", "Wireless Charging"],
    safety_features: ["SmartSense", "Blind Spot Collision Avoidance", "Rear Cross Traffic Avoidance", "Lane Follow Assist"],
    warranty_basic: "5yr / 60,000 mi",
    warranty_powertrain: "10yr / 100,000 mi",
    warranty_roadside: "5yr / unlimited mi",
    photos: ["/vehicles/hyundai-tucson-1.jpg", "/vehicles/hyundai-tucson-2.jpg"],
    video_url: null,
    days_on_lot: 7,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  buildVehicle({
    vehicle_id: "veh_023",
    year: 2023,
    make: "Hyundai",
    model: "Santa Fe",
    trim: "Calligraphy",
    condition: "Used",
    body_style: "SUV",
    stock_number: "H232301",
    vin: vin("5NMS5DAL5PH230023"),
    exterior_color_label: "Quartz White",
    exterior_color_hex: "#EDEBD7",
    interior_color: "Nappa Leather Black",
    interior_material: "Leather",
    transmission: "DCT",
    drivetrain: "AWD",
    engine: "2.5L I4 Turbo",
    cylinders: 4,
    horsepower: 281,
    torque: 311,
    fuel_type: "Gasoline",
    mpg_city: 22,
    mpg_hwy: 28,
    ev_range_miles: null,
    mileage: 19500,
    msrp: 45550,
    sale_price: 36750,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 6.4,
    finance_term_months: 60,
    finance_down_payment: 4000,
    factory_packages: ["Calligraphy Pkg"],
    addon_options: [],
    standard_features: ["12.3\" Digital Cluster", "Harman Kardon Audio", "Heated/Ventilated Seats", "Panoramic Sunroof"],
    safety_features: ["SmartSense", "Blind Spot Avoidance", "Safe Exit Assist", "Remote Smart Park"],
    warranty_basic: "5yr / 60,000 mi",
    warranty_powertrain: "10yr / 100,000 mi",
    warranty_roadside: "5yr / unlimited mi",
    photos: ["/vehicles/hyundai-santafe-1.jpg", "/vehicles/hyundai-santafe-2.jpg"],
    video_url: null,
    days_on_lot: 33,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=5NMS5DAL5PH230023",
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_024",
    year: 2024,
    make: "Hyundai",
    model: "Ioniq 5",
    trim: "Limited AWD",
    condition: "New",
    body_style: "SUV",
    stock_number: "H242401",
    vin: vin("KM8KRDAF9RU240024"),
    exterior_color_label: "Digital Teal",
    exterior_color_hex: "#2E8B7E",
    interior_color: "Dark Pebble Gray / Dove Gray",
    interior_material: "Leatherette",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "Dual Motor Electric",
    cylinders: 0,
    horsepower: 320,
    torque: 446,
    fuel_type: "Electric",
    mpg_city: 0,
    mpg_hwy: 0,
    ev_range_miles: 266,
    mileage: 8,
    msrp: 55920,
    sale_price: 52990,
    dealer_discount: 1930,
    manufacturer_incentive: 1000,
    finance_apr: 4.9,
    finance_term_months: 72,
    finance_down_payment: 5000,
    factory_packages: ["Shooting Star Matte Paint"],
    addon_options: [],
    standard_features: ["12.3\" Dual Screens", "Bose Audio", "Relaxation Seats", "Vehicle-to-Load", "Highway Driving Assist 2"],
    safety_features: ["SmartSense", "Blind Spot Avoidance", "Remote Smart Park", "Surround View Monitor"],
    warranty_basic: "5yr / 60,000 mi",
    warranty_powertrain: "10yr / 100,000 mi",
    warranty_roadside: "5yr / unlimited mi",
    photos: ["/vehicles/hyundai-ioniq5-1.jpg", "/vehicles/hyundai-ioniq5-2.jpg", "/vehicles/hyundai-ioniq5-3.jpg"],
    video_url: "https://videos.example.com/ioniq5-walkaround.mp4",
    days_on_lot: 4,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  // ---- Ram -----------------------------------------------------------------
  buildVehicle({
    vehicle_id: "veh_025",
    year: 2024,
    make: "Ram",
    model: "1500",
    trim: "Laramie Crew Cab",
    condition: "New",
    body_style: "Truck",
    stock_number: "R242501",
    vin: vin("1C6SRFJT5RN250025"),
    exterior_color_label: "Patriot Blue Pearl",
    exterior_color_hex: "#1E3A5F",
    interior_color: "Black / Mountain Brown Leather",
    interior_material: "Leather",
    transmission: "Automatic",
    drivetrain: "4WD",
    engine: "5.7L V8 HEMI eTorque",
    cylinders: 8,
    horsepower: 395,
    torque: 410,
    fuel_type: "Gasoline",
    mpg_city: 17,
    mpg_hwy: 23,
    ev_range_miles: null,
    mileage: 20,
    msrp: 62840,
    sale_price: 58995,
    dealer_discount: 2845,
    manufacturer_incentive: 1000,
    finance_apr: 5.9,
    finance_term_months: 72,
    finance_down_payment: 6000,
    factory_packages: ["Level 1 Equipment Group", "Tow Pkg"],
    addon_options: ["Spray-in bedliner", "Mopar running boards"],
    standard_features: ["Uconnect 5 NAV", "12\" Touchscreen", "Heated/Ventilated Seats", "Remote Start"],
    safety_features: ["Blind Spot Monitor", "Rear Cross Path Detection", "Forward Collision Warning", "Full Speed FCA"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "5yr / 60,000 mi",
    photos: ["/vehicles/ram-1500-1.jpg", "/vehicles/ram-1500-2.jpg", "/vehicles/ram-1500-3.jpg"],
    video_url: null,
    days_on_lot: 25,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  // ---- Additional variety vehicles -----------------------------------------
  buildVehicle({
    vehicle_id: "veh_026",
    year: 2021,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    condition: "Used",
    body_style: "Sedan",
    stock_number: "H212601",
    vin: vin("2HGFE2F50MH260026"),
    exterior_color_label: "Sonic Gray Pearl",
    exterior_color_hex: "#8E8E8E",
    interior_color: "Black Cloth",
    interior_material: "Cloth",
    transmission: "CVT",
    drivetrain: "FWD",
    engine: "2.0L I4",
    cylinders: 4,
    horsepower: 158,
    torque: 138,
    fuel_type: "Gasoline",
    mpg_city: 30,
    mpg_hwy: 37,
    ev_range_miles: null,
    mileage: 48200,
    msrp: 24650,
    sale_price: 18995,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 7.4,
    finance_term_months: 48,
    finance_down_payment: 2000,
    factory_packages: [],
    addon_options: [],
    standard_features: ["Apple CarPlay", "Android Auto", "Adaptive Cruise"],
    safety_features: ["Honda Sensing", "Collision Mitigation Braking", "Road Departure Mitigation"],
    warranty_basic: "Expired",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "Expired",
    photos: ["/vehicles/honda-civic-used-1.jpg", "/vehicles/honda-civic-used-2.jpg"],
    video_url: null,
    days_on_lot: 60,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=2HGFE2F50MH260026",
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_027",
    year: 2024,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    condition: "New",
    body_style: "Sedan",
    stock_number: "T242701",
    vin: vin("4T1C11AK7RU270027"),
    exterior_color_label: "Celestial Silver Metallic",
    exterior_color_hex: "#B8B8B8",
    interior_color: "Ash Fabric",
    interior_material: "Cloth",
    transmission: "Automatic",
    drivetrain: "FWD",
    engine: "2.5L I4 Dynamic Force",
    cylinders: 4,
    horsepower: 203,
    torque: 184,
    fuel_type: "Gasoline",
    mpg_city: 28,
    mpg_hwy: 39,
    ev_range_miles: null,
    mileage: 6,
    msrp: 29495,
    sale_price: 28250,
    dealer_discount: 745,
    manufacturer_incentive: 500,
    finance_apr: 5.9,
    finance_term_months: 72,
    finance_down_payment: 2000,
    factory_packages: [],
    addon_options: ["All-weather floor liners"],
    standard_features: ["Apple CarPlay", "Android Auto", "Toyota Audio Multimedia"],
    safety_features: ["Toyota Safety Sense 3.0", "Lane Departure Alert", "Pre-Collision System"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "2yr / 25,000 mi",
    photos: ["/vehicles/toyota-camry-le-1.jpg", "/vehicles/toyota-camry-le-2.jpg"],
    video_url: null,
    days_on_lot: 15,
    dealer_id: "dealer_002",
    dealer_distance_miles: 12.8,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_028",
    year: 2020,
    make: "Ford",
    model: "F-150",
    trim: "Lariat",
    condition: "Used",
    body_style: "Truck",
    stock_number: "F202801",
    vin: vin("1FTEW1E56LFA28028"),
    exterior_color_label: "Magma Red Metallic",
    exterior_color_hex: "#6E1F1F",
    interior_color: "Kingsville Java Leather",
    interior_material: "Leather",
    transmission: "Automatic",
    drivetrain: "4WD",
    engine: "5.0L V8",
    cylinders: 8,
    horsepower: 400,
    torque: 410,
    fuel_type: "Gasoline",
    mpg_city: 16,
    mpg_hwy: 22,
    ev_range_miles: null,
    mileage: 67800,
    msrp: 58700,
    sale_price: 35500,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 7.9,
    finance_term_months: 48,
    finance_down_payment: 4000,
    factory_packages: ["FX4 Off-Road Pkg"],
    addon_options: [],
    standard_features: ["Sync 3", "B&O Audio", "Heated/Cooled Seats", "Navigation"],
    safety_features: ["Pre-Collision Assist", "Blind Spot Monitor", "Rear View Camera"],
    warranty_basic: "Expired",
    warranty_powertrain: "Expired",
    warranty_roadside: "Expired",
    photos: ["/vehicles/ford-f150-used-1.jpg", "/vehicles/ford-f150-used-2.jpg"],
    video_url: null,
    days_on_lot: 72,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=1FTEW1E56LFA28028",
    price_drop_flag: true,
    new_listing_flag: false,
  }),

  buildVehicle({
    vehicle_id: "veh_029",
    year: 2024,
    make: "Chevrolet",
    model: "Equinox",
    trim: "LT",
    condition: "New",
    body_style: "SUV",
    stock_number: "C242901",
    vin: vin("3GNAXKEV1RS290029"),
    exterior_color_label: "Sterling Gray Metallic",
    exterior_color_hex: "#5A5A5A",
    interior_color: "Jet Black Cloth",
    interior_material: "Cloth",
    transmission: "Automatic",
    drivetrain: "AWD",
    engine: "1.5L I4 Turbo",
    cylinders: 4,
    horsepower: 175,
    torque: 203,
    fuel_type: "Gasoline",
    mpg_city: 26,
    mpg_hwy: 31,
    ev_range_miles: null,
    mileage: 12,
    msrp: 32995,
    sale_price: 30499,
    dealer_discount: 1996,
    manufacturer_incentive: 500,
    finance_apr: 4.9,
    finance_term_months: 72,
    finance_down_payment: 2500,
    factory_packages: ["LT Confidence & Convenience Pkg"],
    addon_options: ["Roof rack cross rails"],
    standard_features: ["Apple CarPlay", "Android Auto", "Wireless Charging", "Heated Seats"],
    safety_features: ["Chevy Safety Assist", "Blind Spot Alert", "Rear Cross Traffic", "Lane Change Alert"],
    warranty_basic: "3yr / 36,000 mi",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "5yr / 60,000 mi",
    photos: ["/vehicles/chevrolet-equinox-lt-1.jpg", "/vehicles/chevrolet-equinox-lt-2.jpg"],
    video_url: null,
    days_on_lot: 9,
    dealer_id: "dealer_003",
    dealer_distance_miles: 22.1,
    carfax_flag: false,
    carfax_url: null,
    price_drop_flag: false,
    new_listing_flag: true,
  }),

  buildVehicle({
    vehicle_id: "veh_030",
    year: 2022,
    make: "Toyota",
    model: "RAV4",
    trim: "Hybrid XSE",
    condition: "Used",
    body_style: "SUV",
    stock_number: "T222901",
    vin: vin("JTMRWRFV1ND300030"),
    exterior_color_label: "Magnetic Gray Metallic",
    exterior_color_hex: "#616161",
    interior_color: "Black SofTex",
    interior_material: "Leatherette",
    transmission: "CVT",
    drivetrain: "AWD",
    engine: "2.5L I4 Hybrid",
    cylinders: 4,
    horsepower: 219,
    torque: 163,
    fuel_type: "Hybrid",
    mpg_city: 41,
    mpg_hwy: 38,
    ev_range_miles: null,
    mileage: 28900,
    msrp: 39210,
    sale_price: 32450,
    dealer_discount: 0,
    manufacturer_incentive: 0,
    finance_apr: 6.4,
    finance_term_months: 60,
    finance_down_payment: 3000,
    factory_packages: ["Weather Pkg"],
    addon_options: [],
    standard_features: ["Apple CarPlay", "Android Auto", "JBL Audio", "Moonroof", "Power Liftgate"],
    safety_features: ["Toyota Safety Sense 2.5+", "Blind Spot Monitor", "Rear Cross Traffic Alert"],
    warranty_basic: "Expired",
    warranty_powertrain: "5yr / 60,000 mi",
    warranty_roadside: "Expired",
    photos: ["/vehicles/toyota-rav4-hybrid-1.jpg", "/vehicles/toyota-rav4-hybrid-2.jpg"],
    video_url: null,
    days_on_lot: 20,
    dealer_id: "dealer_001",
    dealer_distance_miles: 5.2,
    carfax_flag: true,
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?partner=ABC_0&vin=JTMRWRFV1ND300030",
    price_drop_flag: false,
    new_listing_flag: false,
  }),
];
